### ISSUE TITLE
bug in determining longer and shorter string

### ISSUE THREAD

**Issue by zichong** [masatana/go-textdistance#3]
```go
var longer []rune
var shorter []rune
if len(s1) > len(s2) {
	longer = []rune(s1)
	shorter = []rune(s2)
} else {
	longer = []rune(s2)
	shorter = []rune(s1)
}
```

This does not work well when s1 or s2 contains non unicode rune.
For instance, let s1 = "helloworld" and s2 = "hello我的世界", and length of s1 and s2 would be 10 and 13. Then s2 is the longer one according to current code.
But s1 should be the longer one since we calculate JaroDistance by rune.

**Comment by masatana** [comment]
Close this issue as the fix is merged.
