### ISSUE TITLE
Doesn't work on Raspberry Pi 4

### ISSUE THREAD

**Issue by xoco70** [masatana/go-textdistance#6]
I got this message when trying to build the addic7ed project that is using your plugin.

Also used on MacOS, and working well.

```
pi@raspberrypi:~/go/src/github.com/addic7ed $ go build
# github.com/masatana/go-textdistance
../../../pkg/mod/github.com/masatana/go-textdistance@v0.0.0-20171214133840-59954f2a9d67/util.go:7:12: constant 9223372036854775807 overflows int
```

**Comment by masatana** [comment]
Could you give me the project URL?

**Comment by xoco70** [comment]
https://github.com/matcornic/addic7ed

**Comment by masatana** [comment]
Seems like you are hitting this.

https://github.com/golang/go/issues/23086
